export enum CollectionsActionTypes {
    GET_COLLECTIONS = 'GET_COLLECTIONS',
    CREATE_COLLECTION = 'CREATE_COLLECTION',
    UPDATE_COLLECTION = 'UPDATE_COLLECTION',
    GET_COLLECTION = 'GET_COLLECTION',
    DELETE_COLLECTION = 'DELETE_COLLECTION',
}

export enum LinksActionTypes {
    GET_LINKS = 'GET_LINKS',
    CREATE_LINK = 'CREATE_LINK',
    UPDATE_LINK = 'UPDATE_LINK',
    GET_LINK = 'GET_LINK',
    DELETE_LINK = 'DELETE_LINK',
}
